### ISSUE TITLE
Dependabot for Security Updates

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-quickstart-typescript#513]
Configure Dependabot to provide security updates for npm.

```yaml
version: 2
updates:
   - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
```

https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
