### ISSUE TITLE
Dependabot PRs can't push to GHCR.io

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-quickstart-typescript#615]
Dependabot PRs can't create packages.  This can likely be fixed by setting permissions for the build job.

```
  builds:
    name: Builds
    runs-on: ubuntu-latest
    permissions:
      packages: write
```
